// FastJsonDL — basic usage example
//
// Demonstrates how to initialise the EPD panel, build a JSON layout, register
// custom fonts, and render everything using FastJsonDL.
//
// Target board : M5Paper S3 (ESP32-S3) — change BB_PANEL_M5PAPERS3 and the
//                font pointers to match your own hardware / font set.

#include <stdio.h>
#include "FastEPD.h"
#include "FastJsonDL.h"

// ---------------------------------------------------------------------------
// Font data — MUST be replaced with a real font generated by the FastEPD
// fontconvert tool (see FastEPD/fontconvert/README.md).
//
// To generate Ubuntu40.h from a TTF file:
//   ./fontconvert Ubuntu.ttf 40 > Ubuntu40.h
// Then #include "Ubuntu40.h" and remove the extern declaration below.
//
// Without valid font data the drawString item will produce no visible output.
// ---------------------------------------------------------------------------
extern const uint8_t Ubuntu40[];   // declaration only; provide the definition
                                   // in a separate font source file.

// Font registry: maps JSON "font" field values to in-memory font data.
static const FastJsonDLFont fonts[] = {
    { "Ubuntu40", Ubuntu40 },
};

// ---------------------------------------------------------------------------
// JSON layout
// ---------------------------------------------------------------------------
// Minimal font-diagnostic layout:
// - Force 4BPP (0..15 greyscale).
// - Clear the frame buffer to white.
// - Draw one black text item (c:0) with no background shapes.
//
// NOTE — y coordinate for drawString:
// When a BB-format font is loaded (as produced by FastEPD fontconvert), the y
// value is the TEXT BASELINE, not the top-left of the glyph.  Ubuntu40 has an
// ascender height of approximately 50 pixels, so the glyph top sits at
// (y - 50).  Using "y": 10 would place the top of the characters at y = -40,
// entirely off-screen and silently invisible.  Always set y >= font ascender.
static const char LAYOUT_JSON[] = R"({
  "display_bpp": 4,
  "clear": true,
  "items": [
    {
      "type": "drawString",
      "font": "Ubuntu40",
      "string": "Hello from FastJsonDL!",
      "x": 10,
      "y": 70,
      "c": 0
    }
  ]
})";

// ---------------------------------------------------------------------------
// app_main
// ---------------------------------------------------------------------------

// Using heap-allocated pointers avoids a Store access fault on RISC-V targets
// (e.g. ESP32-C5) where constructing a large C++ object in BSS/static storage
// inside app_main() can crash inside bbepInitPanel().  This matches the
// lifecycle used in production C5 firmware.
static FASTEPD      *epaper = nullptr;
static FastJsonDL   *dl     = nullptr;

extern "C" void app_main(void)
{
    // Allocate the EPD driver on the heap.
    epaper = new FASTEPD();

    // Initialise the panel.  Replace BB_PANEL_M5PAPERS3 with the constant
    // that matches your hardware (see the BB_PANEL_* enum in FastEPD.h).
    int rc = epaper->initPanel(BB_PANEL_M5PAPERS3);
    if (rc != BBEP_SUCCESS) {
        printf("EPD init failed (%d)\n", rc);
        return;
    }

    // Optional: override the active pixel area and apply mirror/rotation flags.
    // Remove or adjust for your panel dimensions and orientation.
    // epaper->setPanelSize(EPD_WIDTH, EPD_HEIGHT, BB_PANEL_FLAG_MIRROR_X);

    // Optional: select the rendering bit-depth.
    //   BB_MODE_1BPP — 1-bit black/white (fastest update)
    //   BB_MODE_2BPP — 4 grey levels
    //   BB_MODE_4BPP — 16 grey levels (set "display_bpp": 4 in JSON too)
    // epaper->setMode(BB_MODE_4BPP);

    // Build the renderer on the heap and register the font table.
    dl = new FastJsonDL(*epaper);
    dl->setFontRegistry(fonts, sizeof(fonts) / sizeof(fonts[0]));

    // Render the JSON layout.
    printf("FastJsonDL: rendering layout...\n");
    if (!dl->renderJsonString(LAYOUT_JSON)) {
        printf("FastJsonDL error: %s\n", dl->getLastError());
        return;
    }
    printf("FastJsonDL: render OK, updating panel\n");

    // Push the frame buffer to the physical display.
    epaper->fullUpdate();
}
